U2DJ2/moim-today

backend/src/main/java/booki_today/domain/category/CategoryType.java
backend/src/main/java/booki_today/domain/member/LoginType.java
backend/src/main/java/booki_today/persistence/entity/BaseTimeEntity.java
backend/src/main/java/booki_today/persistence/entity/category/CategoryJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/created_booki/CreatedBookiJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/email_certification_number/EmailCertificationNumberJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/invitation_link/InvitationLinkJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/member/MemberJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/participated_booki/ParticipatedBookiJpaEntity.java
backend/src/main/java/booki_today/persistence/entity/university/UniversityJpaEntity.java
backend/src/main/java/booki_today/persistence/repository/category/CategoryJpaRepository.java
backend/src/main/java/booki_today/persistence/repository/category/CategoryRepository.java
backend/src/main/java/booki_today/persistence/repository/category/CategoryRepositoryImpl.java
backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationJpaRepository.java
backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationNumberRepository.java
backend/src/main/java/booki_today/persistence/repository/email_certification_number/EmailCertificationNumberRepositoryImpl.java
backend/src/main/java/booki_today/persistence/repository/university/UniversityJpaRepository.java
backend/src/main/java/booki_today/persistence/repository/university/UniversityRepository.java
backend/src/main/java/booki_today/persistence/repository/university/UniversityRepositoryImpl.java

> #10 
BaseTimeEntity 추가
대학교 - University
카테고리 - Category
이메일 인증 번호 - EmailCertificationNumber
회원 컬럼 수정 - Member
close #10

[BE] Persistence Layer 구성 추가

---

backend/src/test/java/booki_today/util/ControllerTest.java

> #21 
> ControllerTest setUp 변경, initController 추가

[BE] Controller 테스트 페이크 객체 사용하는 방식으로 변경

---

backend/build.gradle
backend/src/main/java/booki_today/application/file/AmazonS3Service.java
backend/src/main/java/booki_today/application/file/FileService.java
backend/src/main/java/booki_today/application/mail/AmazonSesService.java
backend/src/main/java/booki_today/application/mail/MailService.java
backend/src/main/java/booki_today/dto/file/FileAddRequest.java
backend/src/main/java/booki_today/dto/file/FileDeleteRequest.java
backend/src/main/java/booki_today/dto/file/FileInfoResponse.java
backend/src/main/java/booki_today/dto/mail/MailSendRequest.java
backend/src/main/java/booki_today/global/annotation/Implement.java
backend/src/main/java/booki_today/global/config/AwsConfig.java
backend/src/main/java/booki_today/global/constant/FileExceptionConstant.java
backend/src/main/java/booki_today/global/constant/MailExceptionConstant.java
backend/src/main/java/booki_today/implement/file/FileRemover.java
backend/src/main/java/booki_today/implement/file/FileUploader.java
backend/src/main/java/booki_today/implement/mail/MailSender.java
backend/src/main/java/booki_today/presentation/file/FileController.java
backend/src/main/java/booki_today/presentation/mail/MailController.java
backend/src/main/resources/templates/authenticationMail.html
backend/src/test/java/booki_today/fake_class/FakeFileService.java
backend/src/test/java/booki_today/implement/mail/MailSenderTest.java
backend/src/test/java/booki_today/presentation/file/FileControllerTest.java

> #14 
> 아마존 SES 이메일 전송 기능
아마존 SES 이메일 전송 기능을 이용해서 사용자에게 인증번호 전송하는 기능
아마존 S3 이용한 파일 업로드 기능
아마존 S3 이용한 업로드했던 파일 삭제 기능
>  파일 디렉토리 구조가 많이 추가됐습니다 한번 확인해주세요!
테스트 코드가 외부에 의존하지 않도록 MockMVC 테스트와 페이크 객체, 이메일 Mock 객체를 사용했습니다 리뷰 부탁드려요 😊
closes: #14

[BE] : 아마존 S3 및 SES 관련 파일 업로드 삭제 메일 전송 기능 구현

---

backend/src/main/java/moim_today/dto/department/DepartmentInfoResponse.java
backend/src/main/java/moim_today/implement/university/UniversityUpdater.java
backend/src/main/java/moim_today/persistence/repository/department/DepartmentRepositoryImpl.java
backend/src/test/java/moim_today/implement/university/UniversityUpdaterTest.java

Optional 오류 hotfix

---

backend/src/main/java/moim_today/application/auth/AuthService.java
backend/src/main/java/moim_today/application/auth/AuthServiceImpl.java
backend/src/main/java/moim_today/global/argumentresolver/MemberLoginArgumentResolver.java
backend/src/main/java/moim_today/global/config/WebConfig.java
backend/src/main/java/moim_today/global/interceptor/MemberLoginInterceptor.java
backend/src/main/java/moim_today/implement/member/AuthManager.java
backend/src/main/java/moim_today/presentation/auth/AuthController.java
backend/src/test/java/moim_today/fake_class/auth/FakeAuthService.java
backend/src/test/java/moim_today/fake_class/global/FakeInterceptor.java
backend/src/test/java/moim_today/implement/member/AuthManagerTest.java
backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java
backend/src/test/java/moim_today/util/ControllerTest.java
backend/src/test/java/moim_today/util/ImplementTest.java

> #43 
* 로그아웃 기능 구현
* WebConfig 인터셉터 Path 오류 수정
* 인터셉터 Json 파싱 로직 ArgumentResolver로 이동
* 로그아웃 기능 테스트
this closes #43

[BE] 로그아웃 기능 구현

---

backend/src/main/java/moim_today/application/schedule/ScheduleService.java
backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
backend/src/main/java/moim_today/dto/schedule/ScheduleCreateRequest.java
backend/src/main/java/moim_today/dto/schedule/ScheduleDeleteRequest.java
backend/src/main/java/moim_today/dto/schedule/ScheduleUpdateRequest.java
backend/src/main/java/moim_today/global/constant/exception/ScheduleExceptionConstant.java
backend/src/main/java/moim_today/implement/schedule/ScheduleAppender.java
backend/src/main/java/moim_today/implement/schedule/ScheduleDeleter.java
backend/src/main/java/moim_today/implement/schedule/ScheduleUpdater.java
backend/src/main/java/moim_today/persistence/entity/schedule/ScheduleJpaEntity.java
backend/src/main/java/moim_today/persistence/repository/schedule/ScheduleRepository.java
backend/src/main/java/moim_today/persistence/repository/schedule/ScheduleRepositoryImpl.java
backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
backend/src/test/java/moim_today/implement/schedule/ScheduleAppenderTest.java
backend/src/test/java/moim_today/implement/schedule/ScheduleDeleterTest.java
backend/src/test/java/moim_today/implement/schedule/ScheduleUpdaterTest.java
backend/src/test/java/moim_today/persistence/entity/schedule/ScheduleJpaEntityTest.java
backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java
backend/src/test/java/moim_today/util/ControllerTest.java
backend/src/test/java/moim_today/util/TestConstant.java

> #56 
> 스케줄 등록
스케줄 수정
스케줄 삭제
테스트 코드 작성
> 스케줄 등록/수정시 해당 시간대에 이미 다른 스케줄이 있는지, 회원의 스케줄인지, 존재하는 스케줄인지 검증하는 로직이 많습니다.
테스트 코드를 중점적으로 확인해주시면 될 것 같습니당

[BE] 개인 일정 등록/수정/삭제

---

backend/src/main/java/moim_today/global/config/WebConfig.java

> #74 
> 프론트엔드가 백엔드 API에 접근 가능하도록 CORS 설정

[BE] feat : CORS 설정

---

backend/src/test/java/moim_today/implement/university/UniversityUpdaterTest.java

[BE] 테스트 코드 오류 수정

---

backend/src/main/resources/logback-prod.xml

> #82 
> 하루 단위로 info, error 로그 남기도록 했습니다.
yml 설정 바꿔서 github actions 설정에 추가했고 logback.xml 파일 작성하였습니다.

[BE] chore : 로그 설정

---

backend/src/main/java/moim_today/domain/member/MemberSession.java
backend/src/main/java/moim_today/dto/auth/MemberLoginRequest.java
backend/src/main/java/moim_today/global/constant/NumberConstant.java
backend/src/main/java/moim_today/implement/member/AuthManager.java
backend/src/test/java/moim_today/implement/member/AuthManagerTest.java
backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java

[BE] refactor : 로그인 유지 여부 추가

---

backend/src/main/java/moim_today/global/config/WebConfig.java

[BE] feat : CORS header 설정 추가

---

backend/src/main/java/moim_today/global/config/WebConfig.java

[BE] main branch 병합

---

backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java

> #103 
> 다른 회원의 Weekly, Monthly 캘린더 조회
테스트 코드 작성

[BE] 다른 회원의 캘린더 조회

---

frontend/moim_front/src/api/users.js
frontend/moim_front/src/components/AuthLeft/index.jsx
frontend/moim_front/src/components/Authentification/AuthTitle/index.jsx
frontend/moim_front/src/components/Dropdown/Search.jsx
frontend/moim_front/src/components/Dropdown/Simple.jsx
frontend/moim_front/src/components/Modal/ModalTest.jsx
frontend/moim_front/src/pages/Login/index.jsx
frontend/moim_front/src/pages/RegisterPage/Account/index.jsx
frontend/moim_front/src/pages/RegisterPage/AuthCheck/index.jsx
frontend/moim_front/src/pages/RegisterPage/ConfirmModal/index.jsx
frontend/moim_front/src/pages/RegisterPage/Congrats/index.jsx
frontend/moim_front/src/pages/RegisterPage/Personal/index.jsx
frontend/moim_front/src/pages/RegisterPage/School/index.jsx
frontend/moim_front/src/pages/RegisterPage/TimeTable/index.jsx
frontend/moim_front/src/pages/RegisterPage/index.jsx

> 58
> register 페이지 전반적인 UI 작업 완료
> 각 회원가입 페이지 API 연동 완료 (timetable 제외)
> error시 모달창으로 사용자에게 정보 제공
> 모달창 컴포넌트화
> timeTable 부분은 api 연동되는거 확인을 아직 못했습니다.
> 각 페이지에서 error발생시 모달창으로 사용자에게 정보 전달하게 했는데, 그 과정에서 modal에 props사용하여 콘텐츠 내용 바뀌게 해두었습니다!

[FE] 회원가입 UI 및 API 연동

---

backend/src/main/java/moim_today/application/schedule/ScheduleService.java
backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
backend/src/main/java/moim_today/dto/schedule/AvailableTimeForMemberResponse.java
backend/src/main/java/moim_today/dto/schedule/AvailableTimeInMoimResponse.java
backend/src/main/java/moim_today/presentation/schedule/ScheduleController.java
backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java

> #108 
> 특정 회원의 Weekly 가용시간 계산
api url 수정
테스트 코드 작성

[BE] feat : 다른 회원의 가용시간 조회

---

backend/src/main/resources/templates/certificationPage.html
backend/src/main/resources/templates/emailCertificationMail.html

[BE] refactor : 인증 메일 UI 수정

---

backend/src/main/java/moim_today/application/meeting/MeetingService.java
backend/src/main/java/moim_today/application/meeting/MeetingServiceImpl.java
backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/domain/meeting/Meeting.java
backend/src/main/java/moim_today/domain/meeting/enums/MeetingStatus.java
backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
backend/src/main/java/moim_today/dto/meeting/MeetingSimpleResponse.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingJpaRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
backend/src/main/java/moim_today/presentation/meeting/MeetingController.java
backend/src/test/java/moim_today/fake_class/meeting/FakeMeetingService.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
backend/src/test/java/moim_today/presentation/meeting/MeetingControllerTest.java
backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java

> #115 
> 모임의 다가오는/이전 미팅 목록 조회 기능
스케줄 색상 변경

[BE] 다가오는/이전 미팅 조회 

---

backend/src/main/java/moim_today/application/moim/moim/MoimService.java
backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/dto/moim/moim/enums/MoimCategoryDto.java
backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
backend/src/main/java/moim_today/presentation/moim/MoimController.java
backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java

> 모임 리스트 조회시 전체 카테고리로 조회하는 기능 추가
> 테스트 수정

[BE] 모임 리스트 조회시 전체 카테고리 추가

---

backend/src/main/resources/templates/emailCertificationMail.html
backend/src/main/resources/templates/passwordFindMail.html

> #132 
> 메일 포맷 타임리프 오류 있어서 수정합니다

[BE] 메일 포맷 타임리프 오류 수정

---

backend/src/main/java/moim_today/application/member/MemberService.java
backend/src/main/java/moim_today/application/member/MemberServiceImpl.java
backend/src/main/java/moim_today/dto/member/MemberSimpleResponse.java
backend/src/main/java/moim_today/dto/schedule/AvailableTimeInMoimResponse.java
backend/src/main/java/moim_today/global/constant/exception/MemberExceptionConstant.java
backend/src/main/java/moim_today/implement/member/MemberFinder.java
backend/src/main/java/moim_today/persistence/repository/member/MemberRepository.java
backend/src/main/java/moim_today/persistence/repository/member/MemberRepositoryImpl.java
backend/src/main/java/moim_today/presentation/member/MemberController.java
backend/src/test/java/moim_today/fake_class/member/FakeMemberService.java
backend/src/test/java/moim_today/implement/member/MemberFinderTest.java
backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java
backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java

[BE] 모임 생성자 프로필 조회

---

backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
backend/src/main/java/moim_today/global/constant/MailConstant.java
backend/src/main/resources/templates/certificationPage.html

> 스케줄 색상이 눈에 잘 안 들어와서 색상 변경했습니다. 
또 이메일 문구 줄바꿈 추가하였습니다.

[BE] 스케줄 색상 변경

---

backend/src/main/java/moim_today/application/auth/AuthService.java
backend/src/main/java/moim_today/application/auth/AuthServiceImpl.java
backend/src/main/java/moim_today/domain/member/MemberSession.java
backend/src/main/java/moim_today/dto/auth/MemberSessionValidateResponse.java
backend/src/main/java/moim_today/global/config/WebConfig.java
backend/src/main/java/moim_today/presentation/auth/AuthController.java
backend/src/test/java/moim_today/fake_class/auth/FakeAuthService.java
backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java

> 프론트에서 요청한 회원의 세션이 유효한지 검증하는 API 개발

[BE] 회원 세션 유효 검증

---

backend/src/main/java/moim_today/presentation/auth/AuthController.java
backend/src/test/java/moim_today/presentation/auth/AuthControllerTest.java

[BE] refactor : 세션 인증 API URL 변경

---

backend/src/main/java/moim_today/application/member/MemberService.java
backend/src/main/java/moim_today/application/member/MemberServiceImpl.java
backend/src/main/java/moim_today/dto/member/MemberHostResponse.java
backend/src/main/java/moim_today/dto/member/MemberJoinedMoimResponse.java
backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
backend/src/main/java/moim_today/presentation/member/MemberController.java
backend/src/test/java/moim_today/fake_class/member/FakeMemberService.java
backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java

[BE] 회원이 참여한 모임 검증

---

frontend/moim_front/src/components/Calendar/PersonalCalendar.jsx
frontend/moim_front/src/components/CreationModal/index.jsx
frontend/moim_front/src/main.css
frontend/moim_front/src/pages/Home/MoimCreation.jsx
frontend/moim_front/src/pages/MoimJoinPage/AvailableTime/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/MeetingCreation/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/index.jsx
frontend/moim_front/src/pages/RegisterPage/Personal/index.jsx
frontend/moim_front/src/pages/Schedule/PersonalSection.jsx
frontend/moim_front/src/pages/Schedule/index.jsx

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FE] feat : 중요 기능 수정

---

backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java

> 모임 참가시 모임의 미팅 참여 정보를 추가하지 않아서 이후에 참여한 사람이 
모임의 미팅이 보이지 않은 문제가 있어서 기능을 추가하였습니다.

[BE] 모임 참가시 모임의 미팅 참여

---

frontend/moim_front/src/api/moim.js
frontend/moim_front/src/pages/Home/CardContainer/index.jsx
frontend/moim_front/src/pages/MoimDetailPage/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/MeetingCreation/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/index.jsx
frontend/moim_front/src/router/index.jsx

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FE] feat : 작성자 api 연결 및 z-index 수정

---

backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java

[BE] 미팅 정보 조회 쿼리 오류 수정

---

backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingAppender.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java

[BE] 모임 참여시 미팅 정보 저장하도록 수정

---

backend/.gitignore
backend/build.gradle

> #164 
> 테스트 커버리지 설정과 git ignore 설정을 추가하였습니다.

[BE] jacoco 테스트 커버리지 설정

---

backend/src/main/java/moim_today/application/meeting/joined_meeting/JoinedMeetingService.java
backend/src/main/java/moim_today/application/meeting/joined_meeting/JoinedMeetingServiceImpl.java
backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
backend/src/main/java/moim_today/application/schedule/ScheduleService.java
backend/src/main/java/moim_today/application/schedule/ScheduleServiceImpl.java
backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingRemover.java
backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleRemover.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingJpaRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleJpaRepository.java
backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepository.java
backend/src/main/java/moim_today/persistence/repository/schedule/schedule/ScheduleRepositoryImpl.java
backend/src/test/java/moim_today/fake_class/meeting/joined_meeting/FakeJoinedMeetingService.java
backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingRemoverTest.java
backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleRemoverTest.java

> 미팅 삭제시 스케줄, 미팅 참여 정보 삭제를 추가
테스트 코드 작성

[BE] 미팅 삭제시 스케줄, 미팅 참여 정보 삭제 추가

---

backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
backend/src/main/java/moim_today/dto/meeting/meeting/MeetingCreateResponse.java
backend/src/main/java/moim_today/dto/meeting/meeting/MeetingUpdateRequest.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingUpdater.java
backend/src/main/java/moim_today/persistence/entity/meeting/meeting/MeetingJpaEntity.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingUpdaterTest.java
backend/src/test/java/moim_today/persistence/entity/meeting/meeting/MeetingJpaEntityTest.java
backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java

> 미팅 정보 수정
테스트 코드 작성
시간은 수정하지 않고 미팅 의제, 장소만 수정 가능하도록 기능 추가하였습니다.

[BE] 미팅 정보 수정

---

backend/src/main/java/moim_today/domain/schedule/enums/ColorHex.java
backend/src/test/java/moim_today/domain/member/MemberSessionTest.java
backend/src/test/java/moim_today/domain/schedule/ScheduleLocalDateTest.java
backend/src/test/java/moim_today/domain/schedule/ScheduleYearMonthTest.java
backend/src/test/java/moim_today/domain/schedule/enums/AvailableColorHexTest.java
backend/src/test/java/moim_today/domain/schedule/enums/ColorHexTest.java

> 도메인 로직 검증하는 테스트가 부족한 부분이 있어서 도메인 테스트 추가하였습니다.
스케줄 날짜 계산, 색상 계산, 로그인 세션 테스트 추가했어용~

[BE] 스케줄 날짜/색상, 로그인 세션 도메인 테스트

---

backend/src/main/java/moim_today/dto/schedule/AvailableTimeForMemberResponse.java
backend/src/test/java/moim_today/fake_class/schedule/FakeScheduleService.java
backend/src/test/java/moim_today/presentation/schedule/ScheduleControllerTest.java

[BE] fix : calendar 오타 수정

---

backend/src/main/java/moim_today/dto/moim/moim_notice/MoimNoticeSimpleResponse.java
backend/src/test/java/moim_today/fake_class/moim/FakeMoimNoticeService.java
backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java

> 프론트에서 요청하여 모임 공지 리스트 반환시 년/월/일/요일 반환

[BE] 모임 공지 리스트 반환시 년/월/일/요일 반환

---

backend/src/main/java/moim_today/application/mail/NaverMailService.java
backend/src/main/java/moim_today/global/config/MailConfig.java
backend/src/main/java/moim_today/implement/mail/AmazonSMTPMailSender.java
backend/src/main/java/moim_today/implement/mail/MailScheduler.java
backend/src/main/java/moim_today/implement/mail/NaverSMTPMailSender.java
backend/src/main/java/moim_today/implement/mail/SMTPMailSender.java
backend/src/test/java/moim_today/domain/certification/EmailCertificationTest.java

> AWS SES 의 샌드박스 해제가 시연 전까지 불가능할 가능성이 있기 때문에 네이버 서버를 SMTP 로 추가

[BE] SMTP 서버로 네이버 추가

---

backend/src/main/java/moim_today/global/config/TimezoneConfig.java

[BE] 타임존 변경

---

backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
backend/src/main/java/moim_today/global/constant/exception/MeetingExceptionConstant.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingManager.java
backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingManagerTest.java
backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java

> 미팅 생성시 모임 기간 체크
테스트 코드 작성
> 미팅 생성시 해당 모임의 시간대에 맞는지 확인하는 로직 추가하였습니다.
테스트 코드 위주로 봐주시면 될 것 같습니당

[BE] 미팅 생성시 모임 기간 체크

---

backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/global/constant/exception/MoimExceptionConstant.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
backend/src/main/java/moim_today/persistence/entity/moim/moim/MoimJpaEntity.java
backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
backend/src/test/java/moim_today/persistence/entity/moim/moim/MoimJpaEntityTest.java
backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java

> 이미 끝난 모임에 참여할 수 있는 경우를 예외처리 했습니다.

[BE] 날짜 검사를 매개변수로 받도록 수정

---

backend/src/main/resources/static/admin-login.html
backend/src/main/resources/static/js/get-members.js
backend/src/main/resources/static/js/select-departments.js
backend/src/main/resources/static/js/select-universities.js
backend/src/main/resources/static/js/validate-admin.js

[BE] fix : 어드민 페이지 CORS 에러 수정

---

backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentCollectionResponse.java
backend/src/main/java/moim_today/dto/meeting/meeting_comment/MeetingCommentResponse.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
backend/src/main/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentController.java
backend/src/test/java/moim_today/fake_class/meeting/meeting_comment/FakeMeetingCommentService.java
backend/src/test/java/moim_today/presentation/meeting/meeting_comment/MeetingCommentControllerTest.java

[BE] 댓글 개수, 회원 id 추가

---

backend/src/main/java/moim_today/application/member/MemberService.java
backend/src/main/java/moim_today/application/member/MemberServiceImpl.java
backend/src/main/java/moim_today/dto/member/ProfileUpdateRequest.java
backend/src/main/java/moim_today/implement/member/MemberUpdater.java
backend/src/main/java/moim_today/persistence/entity/member/MemberJpaEntity.java
backend/src/main/java/moim_today/presentation/member/MemberController.java
backend/src/test/java/moim_today/fake_class/member/FakeMemberService.java
backend/src/test/java/moim_today/implement/member/MemberUpdaterTest.java
backend/src/test/java/moim_today/persistence/entity/member/MemberJpaEntityTest.java
backend/src/test/java/moim_today/presentation/member/MemberControllerTest.java

[BE] 회원 프로필 수정 필드 변경

---

backend/src/main/java/moim_today/application/moim/moim/MoimService.java
backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/global/constant/NumberConstant.java
backend/src/main/java/moim_today/implement/moim/joined_moim/JoinedMoimFinder.java
backend/src/main/java/moim_today/implement/moim/moim/MoimFinder.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting_comment/MeetingCommentRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepository.java
backend/src/main/java/moim_today/persistence/repository/moim/joined_moim/JoinedMoimRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/moim/moim_notice/MoimNoticeRepositoryImpl.java
backend/src/main/java/moim_today/presentation/moim/MoimController.java
backend/src/test/java/moim_today/fake_class/moim/FakeMoimService.java
backend/src/test/java/moim_today/implement/moim/joined_moim/JoinedMoimFinderTest.java
backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java
backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
backend/src/test/java/moim_today/presentation/moim/MoimControllerTest.java

> 프론트와의 작업 순서를 맞추기 위해 정렬 및 페이징 처리 `commit` 을 `revert`합니다.
> 정렬 및 페이징 처리한 부분은 `be/feat/order-paging branch`에 남아있습니다.

[BE] 정렬 및 페이징 처리 revert

---

backend/src/main/java/moim_today/application/admin/department/AdminDepartmentService.java
backend/src/main/java/moim_today/application/admin/department/AdminDepartmentServiceImpl.java
backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentService.java
backend/src/main/java/moim_today/application/department/request_department/RequestDepartmentServiceImpl.java
backend/src/main/java/moim_today/implement/department/request_department/RequestDepartmentFinder.java
backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepository.java
backend/src/main/java/moim_today/persistence/repository/department/request_department/RequestDepartmentRepositoryImpl.java
backend/src/main/java/moim_today/presentation/admin/AdminController.java
backend/src/main/java/moim_today/presentation/admin/department/AdminDepartmentController.java
backend/src/main/java/moim_today/presentation/department/request_department/RequestDepartmentController.java
backend/src/test/java/moim_today/fake_class/admin/department/FakeAdminDepartmentService.java
backend/src/test/java/moim_today/fake_class/department/request_department/FakeRequestDepartmentService.java
backend/src/test/java/moim_today/implement/department/request_department/RequestDepartmentFinderTest.java
backend/src/test/java/moim_today/presentation/admin/AdminDepartmentControllerTest.java
backend/src/test/java/moim_today/presentation/department/request_department/RequestDepartmentControllerTest.java

> 학과 관리 패키지 수정
대학별 학과 관리
테스트 코드 작성
> 어드민 페이지 기능이 조금 커질 것 같아서 패키지 분리하였습니다.
대학별로 학과 관리할 수 있는 기능을 추가하였습니다.

[BE] 학교별 학과 관리 - 어드민

---

backend/src/main/java/moim_today/application/meeting/joined_meeting/JoinedMeetingService.java
backend/src/main/java/moim_today/application/meeting/joined_meeting/JoinedMeetingServiceImpl.java
backend/src/main/java/moim_today/dto/meeting/meeting/MeetingAttendanceResponse.java
backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingFinder.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
backend/src/main/java/moim_today/presentation/meeting/joined_meeting/JoinedMeetingController.java
backend/src/test/java/moim_today/fake_class/meeting/joined_meeting/FakeJoinedMeetingService.java
backend/src/test/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingFinderTest.java
backend/src/test/java/moim_today/presentation/meeting/joined_meeting/JoinedMeetingControllerTest.java

> 로그인한 회원의 미팅 참여 여부 조회
테스트 코드 작성

[BE] 회원의 미팅 참여 여부 조회

---

backend/src/main/java/moim_today/application/moim/moim/MoimServiceImpl.java
backend/src/main/java/moim_today/global/constant/NumberConstant.java
backend/src/main/java/moim_today/implement/moim/moim/MoimManager.java
backend/src/test/java/moim_today/implement/moim/moim/MoimManagerTest.java
backend/src/test/java/moim_today/presentation/meeting/joined_meeting/JoinedMeetingControllerTest.java

> 모임의 current count 로직이 정상 작동하도록 수정

[BE] 모임 멤버 참여시 카운트 증가 수정

---

backend/src/main/resources/static/admin-login.html
backend/src/main/resources/static/department-addition-inquiry.html
backend/src/main/resources/static/department-management.html
backend/src/main/resources/static/js/get-members.js
backend/src/main/resources/static/js/select-departments.js
backend/src/main/resources/static/js/select-universities.js
backend/src/main/resources/static/js/validate-admin.js
backend/src/main/resources/static/meeting-management.html
backend/src/main/resources/static/member-management.html
backend/src/main/resources/static/moim-management.html
backend/src/main/resources/static/service-inquiry.html

> 어드민 정적 파일에서 요청 URL 수정
> jQuery요청 -> ajax 요청
> select2 라이브러리 제거

[BE] 어드민 정적 파일 수정

---

backend/src/main/java/moim_today/application/admin/moim/AdminMoimService.java
backend/src/main/java/moim_today/implement/mail/MailScheduler.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimJpaRepository.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepository.java
backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
backend/src/main/java/moim_today/presentation/admin/moim/AdminMoimController.java
backend/src/test/java/moim_today/application/admin/moim/AdminMoimServiceTest.java

> 어드민 모임 조회/삭제
테스트 코드 작성
> AdminSession 인터셉터 관련 로직 아직 처리중이라 이 부분만 todo로 남겨두고 작성하였습니다~ 참고 해주세용
테스트도 어드민 관련 기능은 개별적으로 SpringBootTest 하려고 합니당

[BE] 어드민 모임 관리

---

backend/src/main/java/moim_today/persistence/repository/moim/moim/MoimRepositoryImpl.java
backend/src/test/java/moim_today/implement/moim/moim/MoimFinderTest.java

> 모임 리스트 조회/검색 시 끝난 모임은 조회하지 않는다.

[BE] 모임 리스트 조회/검색 시 끝난 모임은 조회X

---

backend/src/main/java/moim_today/implement/mail/MailScheduler.java
backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingUpdater.java
backend/src/main/java/moim_today/presentation/admin/meeting/AdminMeetingController.java
backend/src/main/java/moim_today/presentation/admin/moim/AdminMoimController.java

> 어드민 모임/미팅 AdminSession 적용
스케줄링 메일 전송 추적 로깅 추가

[BE] 어드민 모임/미팅 AdminSession 적용, 로깅 추가

---

backend/src/main/resources/static/js/get-user-inquiries.js
backend/src/main/resources/static/js/submit-inquiry-answer.js

> 운영 서버에서 작동하기 위해 ajax 요청 url 수정

[BE] AJAX 요청 수정

---

backend/src/main/resources/static/js/get-meetings.js
backend/src/main/resources/static/js/get-moims.js
backend/src/main/resources/static/meeting-management.html
backend/src/main/resources/static/moim-management.html

> 모임 관리 어드민 페이지 구현
미팅 관리 어드민 페이지 구현

[BE] 모임, 미팅 어드민 페이지

---

backend/src/main/java/moim_today/application/admin/user_inquiry/UserInquiryService.java
backend/src/main/java/moim_today/implement/admin/user_inquiry/UserInquiryFinder.java
backend/src/main/resources/static/department-management.html
backend/src/main/resources/static/js/get-department-requests.js
backend/src/main/resources/templates/userInquiryResponseMail.html

> 사용자 문의 메일 템플릿 수정
학과 관리 어드민 페이지 UI 수정
사용자 문의 응답시 트랜잭션 내부 호출 오류 수정

[BE] 메일 템플릿 수정, 트랜잭션 내부 호출 오류 수정

---

backend/src/main/resources/static/service-inquiry.html

>  사용자 문의 작성 시 박스 크기를 넘어갈 경우 스크롤 생기도록 수정

[BE] 서비스 문의 답변 작성 시 스크롤 생기도록 수정

---

frontend/moim_front/src/assets/svg/checked.svg
frontend/moim_front/src/assets/svg/unchecked.svg
frontend/moim_front/src/components/AuthLeft/index.jsx
frontend/moim_front/src/components/DetailedRight/index.jsx
frontend/moim_front/src/components/NewModal/index.jsx
frontend/moim_front/src/pages/ManageProfilePage/index.jsx
frontend/moim_front/src/pages/MeetingDetailPage/index.jsx
frontend/moim_front/src/pages/MoimDetailPage/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/MeetingCreation/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/index.jsx
frontend/moim_front/src/pages/NoticeDetailPage/index.jsx
frontend/moim_front/src/router/index.jsx
frontend/moim_front/src/utils/formatDate.js

> 미팅 참여시 멤버 업데이트 및 모달창 추가
> 모달창 컴포넌트화

feat : 미팅 참여시 멤버 업데이트 및 모달창 추가

---

frontend/moim_front/src/pages/Home/MoimCreation.jsx

[FE] feat : 비공개 모임 생성 삭제

---

frontend/moim_front/src/components/AuthRight/index.jsx
frontend/moim_front/src/components/Authentification/AuthTitle/index.jsx
frontend/moim_front/src/components/Calendar/PersonalCalendar.jsx
frontend/moim_front/src/pages/RegisterPage/Account/index.jsx
frontend/moim_front/src/pages/RegisterPage/Congrats/index.jsx
frontend/moim_front/src/pages/RegisterPage/Personal/index.jsx
frontend/moim_front/src/pages/RegisterPage/School/index.jsx
frontend/moim_front/src/pages/RegisterPage/index.jsx

style : 회원 가입 시 반응형 웹 UI 적용

---

backend/src/main/java/moim_today/application/meeting/meeting/MeetingService.java
backend/src/main/java/moim_today/application/meeting/meeting/MeetingServiceImpl.java
backend/src/main/java/moim_today/dto/meeting/meeting/JoinedMeetingDao.java
backend/src/main/java/moim_today/dto/meeting/meeting/JoinedMeetingResponse.java
backend/src/main/java/moim_today/dto/meeting/meeting/MeetingSimpleResponse.java
backend/src/main/java/moim_today/implement/meeting/joined_meeting/JoinedMeetingFinder.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingComposition.java
backend/src/main/java/moim_today/implement/meeting/meeting/MeetingFinder.java
backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleComposition.java
backend/src/main/java/moim_today/implement/schedule/schedule/ScheduleFinder.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/joined_meeting/JoinedMeetingRepositoryImpl.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepository.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
backend/src/main/java/moim_today/presentation/meeting/meeting/MeetingController.java
backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
backend/src/test/java/moim_today/implement/schedule/schedule/ScheduleFinderTest.java
backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java

> 내가 참여한 미팅 조회
내가 참여한 미팅 조회 - 날짜 정보 추가
테스트 코드 작성

[BE] 내가 참여한 미팅 조회

---

backend/src/main/java/moim_today/dto/meeting/meeting/JoinedMeetingDao.java
backend/src/main/java/moim_today/dto/meeting/meeting/JoinedMeetingResponse.java
backend/src/main/java/moim_today/persistence/repository/meeting/meeting/MeetingRepositoryImpl.java
backend/src/test/java/moim_today/fake_class/meeting/meeting/FakeMeetingService.java
backend/src/test/java/moim_today/implement/meeting/meeting/MeetingFinderTest.java
backend/src/test/java/moim_today/presentation/meeting/meeting/MeetingControllerTest.java

[BE] 미팅 관리 API 필드 추가

---

frontend/moim_front/src/assets/ManageLayout/SidebarElement/index.jsx
frontend/moim_front/src/components/Header/index.jsx
frontend/moim_front/src/pages/Manage/Manage.jsx
frontend/moim_front/src/pages/MeetingDetailPage/index.jsx
frontend/moim_front/src/pages/MeetingManagePage/MeetingSection/index.jsx
frontend/moim_front/src/pages/MeetingManagePage/index.jsx
frontend/moim_front/src/pages/MoimDetailPage/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/CardComponent/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/MoimHome/index.jsx
frontend/moim_front/src/pages/MoimJoinPage/index.jsx
frontend/moim_front/src/router/index.jsx

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Style : 모임 가입 전 디테일 페이지 반응형 추가

---

frontend/moim_front/src/pages/MoimDetailPage/index.jsx
frontend/moim_front/src/router/index.jsx

> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

[FE] feat : error handling 및 디테일 페이지 반응형 수정
